title: Nattsu
markdown: kramdown
theme: null
collections:
  notes:
    output: true
    permalink: /notes/:title/
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: note

